### ISSUE TITLE
C3.S13: As a Developer I Should be able to add words and their synonom and change the synonym to a project in search page.

### ISSUE THREAD

**Issue by Khloud-Khalid** [MGhanem/smartsoft-13#179]
Success: The word will be added and automatically sorted lexicographically in the project. If the developer changed the synonym of a word, a method should return this word to the table of storing the synonyms. All keywords added to the project should take the category of the project if not already assigned

Failure: We should be able to check if the word entered is not spam or already existing in the project. And for free users, if the words exceeds 20 words.if the word isn't in the database it should redirect to add word to database. if he word doesn't have synonyms redirect to follow word.

UML @nourhanZ 
Scenario @KareemAliRahman 
Implementation @adamggg 
Documentation+Testing @zoheiry

**Comment by nourhanZ** [comment]
Please refer to my comments on the other issue so please change the same things :)

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman , @nourhanZ , @adamggg , @zoheiry  please review =)

**Comment by zoheiry** [comment]
Khloud in your documentation, all the author tags  are under the name "kareem ali" why is that, and also why are the tests under a comment with the name "kareem  ali" and also, the UML u added is in the folder Company_UMLS/C1/Kareem Ali, it looks like everything on your branch belongs to kareem ali

**Comment by Khloud-Khalid** [comment]
@zoheiry  it's because i pulled kareem's branch :D the tests are not done yet, as for the documentation you will find we are both authors of the same method since he took my method from sprint 1 and added to it and now we're both using it. and no the UML i added is in my folder.

**Comment by zoheiry** [comment]
what documentation am i supposed to review now, they are all under the name
kareem ali and only one with both your names on it

**Comment by Khloud-Khalid** [comment]
@zoheiry well that is the only method i'm using for this story

**Comment by zoheiry** [comment]
docs verified

**Comment by adamggg** [comment]
@Khloud-Khalid code has been reopened. =D

**Comment by Khloud-Khalid** [comment]
@adamggg done.

**Comment by krmali** [comment]
@Khloud-Khalid, There is an error happening when I try to add word, it is related to my_subscription.

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman this is weird, I'm using the method in my_subscription model that decrements the word add but apparently there is no attribute for the word add in the first place!

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman it's all fixed now

**Comment by krmali** [comment]
@Khloud-Khalid , the same error still there "undefined method `word_search' for nil:NilClass" appears when adding a keyword with synonym, another thing is when you signup  and enter the subscription model page it gives you another error, is this part of your story ?
And regarding the add button , can yo shift the 2 selects and the button to the far right , I guess it will better and make thsize of the font inside the button a little bigger.

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman how come i don't get that error?! the whole subscription model thing is not mine and not even part of any of my stories!

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman don't tell me you didn't run rake db:migrate and populate before running -.-

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman done modifying the button

**Comment by krmali** [comment]
@Khloud-Khalid , I did db:migrate and populate.

**Comment by nourhanZ** [comment]
please reference Karim's method you're using in your UML :) 
and end the timeline of the actor with X :)

**Comment by Khloud-Khalid** [comment]
@adamggg , @nourhanZ , @KareemAliRahman I modified the code and UML. please review =)

**Comment by nourhanZ** [comment]
UML verified :)

**Comment by krmali** [comment]
@Khloud-Khalid, you need to specify for the user , whether the word is added of the synonym is changed when displaying the alert, because he/she might have the keyword in his project.

**Comment by krmali** [comment]
@Khloud-Khalid, shift the add button in the word page to the right of the line.

**Comment by krmali** [comment]
@Khloud-Khalid, scenario verified

**Comment by adamggg** [comment]
Check pull request comments =D

**Comment by adamggg** [comment]
code verified =)
